### ISSUE TITLE
getting error in nso 5.7 version

### ISSUE THREAD

**Issue by robthebuilder123** [NSO-developer/cli-netsim-tool#2]
I am getting below error:
```
admin@ncs(config)# netsim create-device device-name R1 ned-id cisco-iosxr-cli-7.38
Error: application communication failure
admin@ncs(config)# 
```
===
logs:
```
<CRIT> 10-Feb-2023::05:05:58.163 nso-0 ncs[75]: - no registration found for callpoint netsim-tool/action of type=external
<CRIT> 10-Feb-2023::05:06:41.226 nso-0 ncs[75]: - no registration found for callpoint netsim-tool/action of type=external
```

**Comment by JohanVikman** [comment]
It looks like the python code haven't registered the action, can you check the python logs?

**Comment by robthebuilder123** [comment]
Hi Johan, Thanks for the instruction.
but the netsim-tool dir has the module, still getting error.

```
root@nso-0:/log# cat ncs-python-vm-cli-netsim-tool.log 
<INFO> 10-Feb-2023::04:01:38.249 cli-netsim-tool MainThread: - Python 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
<INFO> 10-Feb-2023::04:01:38.253 cli-netsim-tool MainThread: - Using callpoint-model: threading
<INFO> 10-Feb-2023::04:01:38.255 cli-netsim-tool MainThread: - Starting...
<INFO> 10-Feb-2023::04:01:38.268 cli-netsim-tool MainThread: - Started
<ERROR> 10-Feb-2023::04:01:38.289 cli-netsim-tool MainThread: - Traceback (most recent call last):
  File "/opt/ncs/ncs-5.7.1/src/ncs/pyapi/ncs_pyvm/startup.py", line 243, in start_components
    pname=pname, cname=cname, main_q=self.msg_sink)
  File "/opt/ncs/ncs-5.7.1/src/ncs/pyapi/ncs_pyvm/ncsthreads.py", line 153, in __init__
    mod = __import__(modname)
  File "/nso/run/state/packages-in-use/4/cli-netsim-tool/python/netsim_tool/main.py", line 23, in <module>
    from shell_commands import NetsimShell
ModuleNotFoundError: No module named 'shell_commands'

root@nso-0:/log# cd
root@nso-0:~# cd /nso/run/state/packages-in-use/4/cli-netsim-tool/python/netsim_tool/
root@nso-0:/nso/run/state/packages-in-use/4/cli-netsim-tool/python/netsim_tool# ls
__init__.py  __pycache__  main.py  main.pyc  shell_commands.py	shell_commands.pyc  test_create_network.py  test_create_network.pyc
root@nso-0:/nso/run/state/packages-in-use/4/cli-netsim-tool/python/netsim_tool# 
```

**Comment by JohanVikman** [comment]
Ok I see the problem, the import is incorrect. There's a fix here https://github.com/NSO-developer/cli-netsim-tool/pull/3

I'll try to get it merged.

**Comment by robthebuilder123** [comment]
Thanks Johan !!!
